
export const userActionTypes = {
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
    CHECK_USER_SESSION_FAILURE: 'CHECK_USER_SESSION_FAILURE',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
   
  };
  